name: Continuous Integration

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.toml'

env:
  UV_VERSION: 0.7.7

jobs:
    lint_and_type_check:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: "3.9"

        - name: Install UV
          run: |
            curl -LsSf "https://astral.sh/uv/${{ env.UV_VERSION }}/install.sh" | sh

        - name: Install dependencies
          run: uv sync

        - name: Run ruff
          run: uv run ruff check snappylapy  --output-format=github

        - name: Run mypy
          run: uv run mypy snappylapy

    test:
        runs-on: ubuntu-latest

        strategy:
          matrix:
            python-version: [3.9, 3.13]

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install UV
          run: |
            curl -LsSf "https://astral.sh/uv/${{ env.UV_VERSION }}/install.sh" | sh

        - name: Install dependencies
          run: uv sync

        - name: Run tests
          run: uv run pytest tests/
